from .AbrirModal import UIAbrirModal
from .ConfiguracionesModal import UIConfiguracionesModal
from .DispositivosModal import UIDispositvoModal
from  .AgregarDispositivoModal import UIAgregarDispositvoModal