from PyQt5 import QtCore, QtGui, QtWidgets
from classes import modal
from resources import *


class UIAgregarDispositvoModal(modal):

    def __init__(self,Parent,session):
        super(UIAgregarDispositvoModal,self).__init__(Parent,session)
        self.setupUi()

    def setupUi(self):
        DispositvoModal = self
        DispositvoModal.setObjectName("DispositvoModal")
        DispositvoModal.setWindowModality(QtCore.Qt.WindowModal)
        DispositvoModal.resize(580, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DispositvoModal.sizePolicy().hasHeightForWidth())
        DispositvoModal.setSizePolicy(sizePolicy)
        DispositvoModal.setMinimumSize(QtCore.QSize(580, 640))
        font = QtGui.QFont()
        font.setFamily("Noto Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        DispositvoModal.setFont(font)
        DispositvoModal.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../.designer/if_16_1751363.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DispositvoModal.setWindowIcon(icon)
        DispositvoModal.setStyleSheet("background-color: rgb(255, 255, 255);")
        DispositvoModal.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.verticalLayout = QtWidgets.QVBoxLayout(DispositvoModal)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MainFrame = QtWidgets.QFrame(DispositvoModal)
        self.MainFrame.setMinimumSize(QtCore.QSize(360, 520))
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TitleFrame = QtWidgets.QFrame(self.MainFrame)
        self.TitleFrame.setMinimumSize(QtCore.QSize(0, 111))
        self.TitleFrame.setMaximumSize(QtCore.QSize(16777215, 111))
        self.TitleFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TitleFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TitleFrame.setObjectName("TitleFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.TitleFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblUDB = QtWidgets.QLabel(self.TitleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUDB.sizePolicy().hasHeightForWidth())
        self.lblUDB.setSizePolicy(sizePolicy)
        self.lblUDB.setMinimumSize(QtCore.QSize(0, 116))
        self.lblUDB.setMaximumSize(QtCore.QSize(16777215, 116))
        self.lblUDB.setStyleSheet("background-color: rgb(65, 105, 225);\n"
"margin:0px;")
        self.lblUDB.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblUDB.setText("")
        self.lblUDB.setPixmap(QtGui.QPixmap(":/source/img/logo.png"))
        self.lblUDB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblUDB.setObjectName("lblUDB")
        self.gridLayout.addWidget(self.lblUDB, 0, 0, 1, 1)
        self.lblSCADA = QtWidgets.QLabel(self.TitleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSCADA.sizePolicy().hasHeightForWidth())
        self.lblSCADA.setSizePolicy(sizePolicy)
        self.lblSCADA.setMinimumSize(QtCore.QSize(250, 116))
        self.lblSCADA.setMaximumSize(QtCore.QSize(16777215, 116))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.lblSCADA.setFont(font)
        self.lblSCADA.setAutoFillBackground(False)
        self.lblSCADA.setStyleSheet("color: rgb(255, 255, 0);background-color: rgb(65, 105, 225);\n"
"margin:0px;")
        self.lblSCADA.setObjectName("lblSCADA")
        self.gridLayout.addWidget(self.lblSCADA, 0, 2, 1, 1)
        self.ExitFrame = QtWidgets.QFrame(self.TitleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExitFrame.sizePolicy().hasHeightForWidth())
        self.ExitFrame.setSizePolicy(sizePolicy)
        self.ExitFrame.setMinimumSize(QtCore.QSize(0, 116))
        self.ExitFrame.setMaximumSize(QtCore.QSize(16777215, 116))
        self.ExitFrame.setStyleSheet("background-color: rgb(65, 105, 225);")
        self.ExitFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ExitFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ExitFrame.setLineWidth(0)
        self.ExitFrame.setObjectName("ExitFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ExitFrame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnExit_2 = QtWidgets.QPushButton(self.ExitFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExit_2.sizePolicy().hasHeightForWidth())
        self.btnExit_2.setSizePolicy(sizePolicy)
        self.btnExit_2.setMaximumSize(QtCore.QSize(32, 32))
        self.btnExit_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnExit_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/source/img/Cancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExit_2.setIcon(icon1)
        self.btnExit_2.setIconSize(QtCore.QSize(24, 24))
        self.btnExit_2.setFlat(True)
        self.btnExit_2.setObjectName("btnExit_2")
        self.gridLayout_4.addWidget(self.btnExit_2, 0, 1, 1, 1)
        self.lblIIE = QtWidgets.QLabel(self.ExitFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblIIE.sizePolicy().hasHeightForWidth())
        self.lblIIE.setSizePolicy(sizePolicy)
        self.lblIIE.setMaximumSize(QtCore.QSize(16777215, 116))
        self.lblIIE.setStyleSheet("background-color: rgb(65, 105, 225);\n"
"margin:0px;")
        self.lblIIE.setText("")
        self.lblIIE.setPixmap(QtGui.QPixmap(":/source/img/iiie.png"))
        self.lblIIE.setScaledContents(False)
        self.lblIIE.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIIE.setObjectName("lblIIE")
        self.gridLayout_4.addWidget(self.lblIIE, 0, 0, 2, 1)
        self.gridLayout.addWidget(self.ExitFrame, 0, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.TitleFrame, 0, QtCore.Qt.AlignTop)
        self.lblTitle = QtWidgets.QLabel(self.MainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitle.sizePolicy().hasHeightForWidth())
        self.lblTitle.setSizePolicy(sizePolicy)
        self.lblTitle.setMinimumSize(QtCore.QSize(0, 26))
        self.lblTitle.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("margin-top:5px;")
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_2.addWidget(self.lblTitle, 0, QtCore.Qt.AlignTop)
        self.groupBox = QtWidgets.QGroupBox(self.MainFrame)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox{margin-left:25px;margin-right:25px;}\n"
"QGroupBox::title{top:0;}")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.lblImagen = QtWidgets.QLabel(self.groupBox)
        self.lblImagen.setGeometry(QtCore.QRect(40, 42, 171, 151))
        self.lblImagen.setText("")
        self.lblImagen.setPixmap(QtGui.QPixmap(":/source/img/NoImage.png"))
        self.lblImagen.setScaledContents(True)
        self.lblImagen.setObjectName("lblImagen")
        self.txtNombre = QtWidgets.QLineEdit(self.groupBox)
        self.txtNombre.setGeometry(QtCore.QRect(320, 60, 161, 21))
        self.txtNombre.setStyleSheet("border-bottom:1px solid black;border-top:none;")
        self.txtNombre.setObjectName("txtNombre")
        self.txtID = QtWidgets.QLineEdit(self.groupBox)
        self.txtID.setGeometry(QtCore.QRect(320, 90, 161, 21))
        self.txtID.setStyleSheet("border-bottom:1px solid black;border-top:none;")
        self.txtID.setObjectName("txtID")
        self.txtToken = QtWidgets.QLineEdit(self.groupBox)
        self.txtToken.setGeometry(QtCore.QRect(320, 120, 161, 21))
        self.txtToken.setStyleSheet("border-bottom:1px solid black;border-top:none;")
        self.txtToken.setObjectName("txtToken")
        self.txtTime = QtWidgets.QSpinBox(self.groupBox)
        self.txtTime.setGeometry(QtCore.QRect(320, 155, 45, 26))
        self.txtTime.setObjectName("txtTime")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(250, 63, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(250, 93, 54, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(250, 125, 54, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(250, 160, 54, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.btnAceptar = QtWidgets.QPushButton(self.groupBox)
        self.btnAceptar.setGeometry(QtCore.QRect(430, 3, 95, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAceptar.sizePolicy().hasHeightForWidth())
        self.btnAceptar.setSizePolicy(sizePolicy)
        self.btnAceptar.setMinimumSize(QtCore.QSize(92, 38))
        self.btnAceptar.setMaximumSize(QtCore.QSize(128, 48))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnAceptar.setFont(font)
        self.btnAceptar.setStyleSheet("border:1px solid green;top:0px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/source/img/OK.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAceptar.setIcon(icon2)
        self.btnAceptar.setIconSize(QtCore.QSize(24, 24))
        self.btnAceptar.setShortcut("")
        self.btnAceptar.setCheckable(False)
        self.btnAceptar.setFlat(True)
        self.btnAceptar.setObjectName("btnAceptar")
        self.btnImportar = QtWidgets.QPushButton(self.groupBox)
        self.btnImportar.setGeometry(QtCore.QRect(330, 3, 95, 40))
        self.btnImportar.setMinimumSize(QtCore.QSize(92, 38))
        self.btnImportar.setMaximumSize(QtCore.QSize(128, 48))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnImportar.setFont(font)
        self.btnImportar.setStyleSheet("border:1px solid green;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/source/img/Importar-SM.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnImportar.setIcon(icon3)
        self.btnImportar.setIconSize(QtCore.QSize(24, 24))
        self.btnImportar.setShortcut("")
        self.btnImportar.setCheckable(False)
        self.btnImportar.setFlat(True)
        self.btnImportar.setObjectName("btnImportar")
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.variablesContent = QtWidgets.QGroupBox(self.MainFrame)
        self.variablesContent.setMinimumSize(QtCore.QSize(0, 225))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.variablesContent.setFont(font)
        self.variablesContent.setStyleSheet("QGroupBox{margin-left:25px;margin-right:25px;}\n"
"QGroupBox::title{top:0;}")
        self.variablesContent.setObjectName("variablesContent")
        self.lblVariablesCount = QtWidgets.QLabel(self.variablesContent)
        self.lblVariablesCount.setGeometry(QtCore.QRect(320, 13, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblVariablesCount.setFont(font)
        self.lblVariablesCount.setObjectName("lblVariablesCount")
        self.btnVariableAgregar = QtWidgets.QPushButton(self.variablesContent)
        self.btnVariableAgregar.setGeometry(QtCore.QRect(430, 0, 95, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnVariableAgregar.sizePolicy().hasHeightForWidth())
        self.btnVariableAgregar.setSizePolicy(sizePolicy)
        self.btnVariableAgregar.setMinimumSize(QtCore.QSize(92, 38))
        self.btnVariableAgregar.setMaximumSize(QtCore.QSize(128, 48))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnVariableAgregar.setFont(font)
        self.btnVariableAgregar.setStyleSheet("border:1px solid green;top:0px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/source/img/Agregar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnVariableAgregar.setIcon(icon4)
        self.btnVariableAgregar.setIconSize(QtCore.QSize(24, 24))
        self.btnVariableAgregar.setShortcut("")
        self.btnVariableAgregar.setCheckable(False)
        self.btnVariableAgregar.setFlat(True)
        self.btnVariableAgregar.setObjectName("btnVariableAgregar")
        self.variablesScroll = QtWidgets.QScrollArea(self.variablesContent)
        self.variablesScroll.setGeometry(QtCore.QRect(28, 73, 505, 141))
        self.variablesScroll.setWidgetResizable(True)
        self.variablesScroll.setObjectName("variablesScroll")
        self.VariableScrollContent = QtWidgets.QWidget()
        self.VariableScrollContent.setGeometry(QtCore.QRect(0, 0, 503, 139))
        self.VariableScrollContent.setObjectName("VariableScrollContent")
        self.variablesScroll.setWidget(self.VariableScrollContent)
        self.lblVariableNombre = QtWidgets.QLabel(self.variablesContent)
        self.lblVariableNombre.setGeometry(QtCore.QRect(45, 45, 65, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblVariableNombre.setFont(font)
        self.lblVariableNombre.setObjectName("lblVariableNombre")
        self.lblVariablePIN = QtWidgets.QLabel(self.variablesContent)
        self.lblVariablePIN.setGeometry(QtCore.QRect(135, 45, 65, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblVariablePIN.setFont(font)
        self.lblVariablePIN.setObjectName("lblVariablePIN")
        self.lblVariableTipo = QtWidgets.QLabel(self.variablesContent)
        self.lblVariableTipo.setGeometry(QtCore.QRect(230, 45, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblVariableTipo.setFont(font)
        self.lblVariableTipo.setObjectName("lblVariableTipo")
        self.lblVariableColor = QtWidgets.QLabel(self.variablesContent)
        self.lblVariableColor.setGeometry(QtCore.QRect(295, 45, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblVariableColor.setFont(font)
        self.lblVariableColor.setObjectName("lblVariableColor")
        self.lblVariableSenal = QtWidgets.QLabel(self.variablesContent)
        self.lblVariableSenal.setGeometry(QtCore.QRect(375, 45, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblVariableSenal.setFont(font)
        self.lblVariableSenal.setObjectName("lblVariableSenal")
        self.lblVariableAccion = QtWidgets.QLabel(self.variablesContent)
        self.lblVariableAccion.setGeometry(QtCore.QRect(450, 45, 65, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblVariableAccion.setFont(font)
        self.lblVariableAccion.setObjectName("lblVariableAccion")
        self.verticalLayout_2.addWidget(self.variablesContent)
        self.verticalLayout.addWidget(self.MainFrame, 0, QtCore.Qt.AlignTop)

        self.retranslateUi(DispositvoModal)
        QtCore.QMetaObject.connectSlotsByName(DispositvoModal)

    def disconnectSignals(self):
        pass

    def retranslateUi(self, DispositvoModal):
        _translate = QtCore.QCoreApplication.translate
        DispositvoModal.setWindowTitle(_translate("DispositvoModal", "Sistema SCADA"))
        self.lblSCADA.setText(_translate("DispositvoModal", "SCADA"))
        self.lblTitle.setText(_translate("DispositvoModal", "Agregar Dispositivo"))
        self.groupBox.setTitle(_translate("DispositvoModal", "Información"))
        self.label.setText(_translate("DispositvoModal", "Nombre:"))
        self.label_2.setText(_translate("DispositvoModal", "ID:"))
        self.label_3.setText(_translate("DispositvoModal", "Token:"))
        self.label_4.setText(_translate("DispositvoModal", "Tiempo:"))
        self.btnAceptar.setText(_translate("DispositvoModal", "Aceptar"))
        self.btnImportar.setText(_translate("DispositvoModal", "Importar"))
        self.variablesContent.setTitle(_translate("DispositvoModal", "Variables"))
        self.lblVariablesCount.setText(_translate("DispositvoModal", "Variables 0/12"))
        self.btnVariableAgregar.setText(_translate("DispositvoModal", "Agregar"))
        self.lblVariableNombre.setText(_translate("DispositvoModal", "Nombre:"))
        self.lblVariablePIN.setText(_translate("DispositvoModal", "Variable:"))
        self.lblVariableTipo.setText(_translate("DispositvoModal", "Tipo:"))
        self.lblVariableColor.setText(_translate("DispositvoModal", "Color:"))
        self.lblVariableSenal.setText(_translate("DispositvoModal", "Señal:"))
        self.lblVariableAccion.setText(_translate("DispositvoModal", "Acciones:"))
