from PyQt5 import QtCore, QtGui, QtWidgets
from classes import widget,device

class UIDispositivoModalWidget(widget):

    def __init__(self, device):
        self.dispositivo = device
        super(UIDispositivoModalWidget,self).__init__()
        self.setupUi()

    def setupUi(self):
        Form = self
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(612, 178)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ProjectFrame = QtWidgets.QFrame(Form)
        self.ProjectFrame.setGeometry(QtCore.QRect(0, 0, 612, 195))
        self.ProjectFrame.setMinimumSize(QtCore.QSize(350, 91))
        self.ProjectFrame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.ProjectFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ProjectFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ProjectFrame.setObjectName("ProjectFrame")
        self.lblImagen = QtWidgets.QLabel(self.ProjectFrame)
        self.lblImagen.setGeometry(QtCore.QRect(10, 15, 171, 151))
        self.lblImagen.setText("")
        self.lblImagen.setPixmap(QtGui.QPixmap(":/source/img/NoImage.png"))
        self.lblImagen.setScaledContents(True)
        self.lblImagen.setObjectName("lblImagen")
        self.InfoFrame = QtWidgets.QFrame(self.ProjectFrame)
        self.InfoFrame.setGeometry(QtCore.QRect(190, 10, 300, 165))
        self.InfoFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.InfoFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.InfoFrame.setLineWidth(0)
        self.InfoFrame.setObjectName("InfoFrame")
        self.lblNombre = QtWidgets.QLabel(self.InfoFrame)
        self.lblNombre.setGeometry(QtCore.QRect(5, 10, 85, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblNombre.setFont(font)
        self.lblNombre.setLineWidth(0)
        self.lblNombre.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblNombre.setObjectName("lblNombre")
        self.lblID = QtWidgets.QLabel(self.InfoFrame)
        self.lblID.setGeometry(QtCore.QRect(5, 40, 85, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblID.setFont(font)
        self.lblID.setLineWidth(0)
        self.lblID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblID.setObjectName("lblID")
        self.lblToken = QtWidgets.QLabel(self.InfoFrame)
        self.lblToken.setGeometry(QtCore.QRect(5, 75, 85, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblToken.setFont(font)
        self.lblToken.setLineWidth(0)
        self.lblToken.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblToken.setObjectName("lblToken")
        self.lblTiempo = QtWidgets.QLabel(self.InfoFrame)
        self.lblTiempo.setGeometry(QtCore.QRect(5, 115, 85, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblTiempo.setFont(font)
        self.lblTiempo.setLineWidth(0)
        self.lblTiempo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTiempo.setObjectName("lblTiempo")
        self.lblVariables = QtWidgets.QLabel(self.InfoFrame)
        self.lblVariables.setGeometry(QtCore.QRect(5, 140, 85, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblVariables.setFont(font)
        self.lblVariables.setLineWidth(0)
        self.lblVariables.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblVariables.setObjectName("lblVariables")
        self.ScrollNombre = QtWidgets.QScrollArea(self.InfoFrame)
        self.ScrollNombre.setGeometry(QtCore.QRect(100, 10, 200, 22))
        self.ScrollNombre.setMinimumSize(QtCore.QSize(110, 20))
        self.ScrollNombre.setMaximumSize(QtCore.QSize(200, 25))
        self.ScrollNombre.setFrameShape(QtWidgets.QFrame.Panel)
        self.ScrollNombre.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ScrollNombre.setLineWidth(0)
        self.ScrollNombre.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ScrollNombre.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ScrollNombre.setWidgetResizable(True)
        self.ScrollNombre.setObjectName("ScrollNombre")
        self.NombreScrollLayout = QtWidgets.QWidget()
        self.NombreScrollLayout.setGeometry(QtCore.QRect(0, 0, 186, 36))
        self.NombreScrollLayout.setObjectName("NombreScrollLayout")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.NombreScrollLayout)
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.txtNombre = QtWidgets.QLabel(self.NombreScrollLayout)
        self.txtNombre.setMaximumSize(QtCore.QSize(16666672, 16666672))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txtNombre.setFont(font)
        self.txtNombre.setLineWidth(0)
        self.txtNombre.setTextFormat(QtCore.Qt.PlainText)
        self.txtNombre.setScaledContents(True)
        self.txtNombre.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtNombre.setWordWrap(True)
        self.txtNombre.setIndent(5)
        self.txtNombre.setObjectName("txtNombre")
        self.vboxlayout.addWidget(self.txtNombre)
        self.ScrollNombre.setWidget(self.NombreScrollLayout)
        self.ScrollID = QtWidgets.QScrollArea(self.InfoFrame)
        self.ScrollID.setGeometry(QtCore.QRect(100, 40, 200, 32))
        self.ScrollID.setMinimumSize(QtCore.QSize(110, 20))
        self.ScrollID.setMaximumSize(QtCore.QSize(200, 100))
        self.ScrollID.setFrameShape(QtWidgets.QFrame.Panel)
        self.ScrollID.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ScrollID.setLineWidth(0)
        self.ScrollID.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ScrollID.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ScrollID.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.ScrollID.setWidgetResizable(False)
        self.ScrollID.setObjectName("ScrollID")
        self.IDScrollLayout = QtWidgets.QWidget()
        self.IDScrollLayout.setGeometry(QtCore.QRect(0, 0, 207, 18))
        self.IDScrollLayout.setObjectName("IDScrollLayout")
        self._2 = QtWidgets.QVBoxLayout(self.IDScrollLayout)
        self._2.setContentsMargins(0, 0, 0, 0)
        self._2.setSpacing(0)
        self._2.setObjectName("_2")
        self.txtID = QtWidgets.QLabel(self.IDScrollLayout)
        self.txtID.setMaximumSize(QtCore.QSize(16666672, 16666672))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtID.setFont(font)
        self.txtID.setLineWidth(0)
        self.txtID.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtID.setWordWrap(True)
        self.txtID.setIndent(-8)
        self.txtID.setObjectName("txtID")
        self._2.addWidget(self.txtID)
        self.ScrollID.setWidget(self.IDScrollLayout)
        self.ScrollToken = QtWidgets.QScrollArea(self.InfoFrame)
        self.ScrollToken.setGeometry(QtCore.QRect(100, 80, 200, 32))
        self.ScrollToken.setMinimumSize(QtCore.QSize(110, 20))
        self.ScrollToken.setMaximumSize(QtCore.QSize(200, 100))
        self.ScrollToken.setFrameShape(QtWidgets.QFrame.Panel)
        self.ScrollToken.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ScrollToken.setLineWidth(0)
        self.ScrollToken.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ScrollToken.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ScrollToken.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.ScrollToken.setWidgetResizable(False)
        self.ScrollToken.setObjectName("ScrollToken")
        self.TokencrollLayout = QtWidgets.QWidget()
        self.TokencrollLayout.setGeometry(QtCore.QRect(-7, 0, 207, 18))
        self.TokencrollLayout.setObjectName("TokencrollLayout")
        self._3 = QtWidgets.QVBoxLayout(self.TokencrollLayout)
        self._3.setContentsMargins(0, 0, 0, 0)
        self._3.setSpacing(0)
        self._3.setObjectName("_3")
        self.txtToken = QtWidgets.QLabel(self.TokencrollLayout)
        self.txtToken.setMaximumSize(QtCore.QSize(16666672, 16666672))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtToken.setFont(font)
        self.txtToken.setLineWidth(0)
        self.txtToken.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtToken.setWordWrap(True)
        self.txtToken.setIndent(-8)
        self.txtToken.setObjectName("txtToken")
        self._3.addWidget(self.txtToken)
        self.ScrollToken.setWidget(self.TokencrollLayout)
        self.txtTiempo = QtWidgets.QLabel(self.InfoFrame)
        self.txtTiempo.setGeometry(QtCore.QRect(100, 115, 150, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txtTiempo.setFont(font)
        self.txtTiempo.setObjectName("txtTiempo")
        self.txtVariables = QtWidgets.QLabel(self.InfoFrame)
        self.txtVariables.setGeometry(QtCore.QRect(100, 140, 150, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txtVariables.setFont(font)
        self.txtVariables.setObjectName("txtVariables")
        self.frame = QtWidgets.QFrame(self.ProjectFrame)
        self.frame.setGeometry(QtCore.QRect(500, 10, 91, 165))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.btnEditar = QtWidgets.QPushButton(self.frame)
        self.btnEditar.setGeometry(QtCore.QRect(10, 70, 38, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEditar.sizePolicy().hasHeightForWidth())
        self.btnEditar.setSizePolicy(sizePolicy)
        self.btnEditar.setMinimumSize(QtCore.QSize(0, 0))
        self.btnEditar.setMaximumSize(QtCore.QSize(128, 48))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnEditar.setFont(font)
        self.btnEditar.setStyleSheet("border:1px solid green;top:0px;")
        self.btnEditar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/source/img/Editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEditar.setIcon(icon)
        self.btnEditar.setIconSize(QtCore.QSize(24, 24))
        self.btnEditar.setShortcut("")
        self.btnEditar.setCheckable(False)
        self.btnEditar.setFlat(True)
        self.btnEditar.setObjectName("btnEditar")
        self.btnEliminar = QtWidgets.QPushButton(self.frame)
        self.btnEliminar.setGeometry(QtCore.QRect(50, 70, 38, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEliminar.sizePolicy().hasHeightForWidth())
        self.btnEliminar.setSizePolicy(sizePolicy)
        self.btnEliminar.setMinimumSize(QtCore.QSize(0, 0))
        self.btnEliminar.setMaximumSize(QtCore.QSize(128, 48))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnEliminar.setFont(font)
        self.btnEliminar.setStyleSheet("border:1px solid green;top:0px;")
        self.btnEliminar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/source/img/Cancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEliminar.setIcon(icon1)
        self.btnEliminar.setIconSize(QtCore.QSize(24, 24))
        self.btnEliminar.setShortcut("")
        self.btnEliminar.setCheckable(False)
        self.btnEliminar.setFlat(True)
        self.btnEliminar.setObjectName("btnEliminar")
        self.btnEliminar_2 = QtWidgets.QPushButton(self.frame)
        self.btnEliminar_2.setGeometry(QtCore.QRect(60, 10, 24, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEliminar_2.sizePolicy().hasHeightForWidth())
        self.btnEliminar_2.setSizePolicy(sizePolicy)
        self.btnEliminar_2.setMinimumSize(QtCore.QSize(0, 0))
        self.btnEliminar_2.setMaximumSize(QtCore.QSize(128, 48))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnEliminar_2.setFont(font)
        self.btnEliminar_2.setStyleSheet("border:1px solid green;top:0px;")
        self.btnEliminar_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/source/img/Copiar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEliminar_2.setIcon(icon2)
        self.btnEliminar_2.setIconSize(QtCore.QSize(24, 24))
        self.btnEliminar_2.setShortcut("")
        self.btnEliminar_2.setCheckable(False)
        self.btnEliminar_2.setFlat(True)
        self.btnEliminar_2.setObjectName("btnEliminar_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblNombre.setText(_translate("Form", "Nombre:"))
        self.lblID.setText(_translate("Form", "ID:"))
        self.lblToken.setText(_translate("Form", "Token:"))
        self.lblTiempo.setText(_translate("Form", "Tiempo:"))
        self.lblVariables.setText(_translate("Form", "# Variables:"))
        self.txtNombre.setText(_translate("Form", "Dispositivo 1; Tipo Lecto de temperatura"))
        self.txtID.setText(_translate("Form", "230037001347343438323536"))
        self.txtToken.setText(_translate("Form", "57f539fb1a8cc926f59ee72f3fd69e4c5adc3945"))
        self.txtTiempo.setText(_translate("Form", "30 Segundos"))
        self.txtVariables.setText(_translate("Form", "4"))