from PyQt5 import QtCore, QtGui, QtWidgets
from classes import widget
from resources import *


class UIVariableWidget(widget):

    def __init__(self):
        super(UIVariableWidget,self).__init__()
        self.setupUi()

    def setupUi(self):
        VariableWidget = self
        VariableWidget.setObjectName("VariableWidget")
        VariableWidget.resize(490, 39)
        VariableWidget.setMinimumSize(QtCore.QSize(150, 25))
        self.MainFrame = QtWidgets.QFrame(VariableWidget)
        self.MainFrame.setGeometry(QtCore.QRect(0, 0, 491, 41))
        self.MainFrame.setMinimumSize(QtCore.QSize(150, 25))
        self.MainFrame.setMaximumSize(QtCore.QSize(16666, 166672))
        self.MainFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setLineWidth(1)
        self.MainFrame.setObjectName("MainFrame")
        self.lblNombreScroll = QtWidgets.QScrollArea(self.MainFrame)
        self.lblNombreScroll.setGeometry(QtCore.QRect(0, 5, 90, 25))
        self.lblNombreScroll.setMinimumSize(QtCore.QSize(65, 20))
        self.lblNombreScroll.setMaximumSize(QtCore.QSize(100, 25))
        self.lblNombreScroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblNombreScroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblNombreScroll.setLineWidth(0)
        self.lblNombreScroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lblNombreScroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lblNombreScroll.setWidgetResizable(True)
        self.lblNombreScroll.setObjectName("lblNombreScroll")
        self.ScrollNombreLayout = QtWidgets.QWidget()
        self.ScrollNombreLayout.setGeometry(QtCore.QRect(0, 0, 90, 25))
        self.ScrollNombreLayout.setObjectName("ScrollNombreLayout")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.ScrollNombreLayout)
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.lblNombre = QtWidgets.QLabel(self.ScrollNombreLayout)
        self.lblNombre.setMaximumSize(QtCore.QSize(16666672, 16666672))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblNombre.setFont(font)
        self.lblNombre.setLineWidth(0)
        self.lblNombre.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lblNombre.setWordWrap(True)
        self.lblNombre.setIndent(5)
        self.lblNombre.setObjectName("lblNombre")
        self.vboxlayout.addWidget(self.lblNombre)
        self.lblNombreScroll.setWidget(self.ScrollNombreLayout)
        self.lblTipo = QtWidgets.QLabel(self.MainFrame)
        self.lblTipo.setGeometry(QtCore.QRect(180, 5, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblTipo.setFont(font)
        self.lblTipo.setStyleSheet("padding-top:5px;")
        self.lblTipo.setLineWidth(0)
        self.lblTipo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTipo.setIndent(-1)
        self.lblTipo.setObjectName("lblTipo")
        self.lblColor = QtWidgets.QLabel(self.MainFrame)
        self.lblColor.setGeometry(QtCore.QRect(250, 5, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblColor.setFont(font)
        self.lblColor.setStyleSheet("padding-top:5px;")
        self.lblColor.setLineWidth(0)
        self.lblColor.setAlignment(QtCore.Qt.AlignCenter)
        self.lblColor.setIndent(-1)
        self.lblColor.setObjectName("lblColor")
        self.lblSel = QtWidgets.QLabel(self.MainFrame)
        self.lblSel.setGeometry(QtCore.QRect(325, 5, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblSel.setFont(font)
        self.lblSel.setStyleSheet("padding-top:5px;")
        self.lblSel.setLineWidth(0)
        self.lblSel.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSel.setIndent(-1)
        self.lblSel.setObjectName("lblSel")
        self.btnAgregar_2 = QtWidgets.QPushButton(self.MainFrame)
        self.btnAgregar_2.setGeometry(QtCore.QRect(415, 0, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAgregar_2.sizePolicy().hasHeightForWidth())
        self.btnAgregar_2.setSizePolicy(sizePolicy)
        self.btnAgregar_2.setMinimumSize(QtCore.QSize(32, 32))
        self.btnAgregar_2.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnAgregar_2.setFont(font)
        self.btnAgregar_2.setStyleSheet("")
        self.btnAgregar_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/source/img/Editar-SM.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAgregar_2.setIcon(icon)
        self.btnAgregar_2.setIconSize(QtCore.QSize(24, 24))
        self.btnAgregar_2.setShortcut("")
        self.btnAgregar_2.setCheckable(False)
        self.btnAgregar_2.setFlat(True)
        self.btnAgregar_2.setObjectName("btnAgregar_2")
        self.btnAgregar_3 = QtWidgets.QPushButton(self.MainFrame)
        self.btnAgregar_3.setGeometry(QtCore.QRect(445, 0, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAgregar_3.sizePolicy().hasHeightForWidth())
        self.btnAgregar_3.setSizePolicy(sizePolicy)
        self.btnAgregar_3.setMinimumSize(QtCore.QSize(32, 32))
        self.btnAgregar_3.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnAgregar_3.setFont(font)
        self.btnAgregar_3.setStyleSheet("")
        self.btnAgregar_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/source/img/Eliminar-SM.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAgregar_3.setIcon(icon1)
        self.btnAgregar_3.setIconSize(QtCore.QSize(24, 24))
        self.btnAgregar_3.setShortcut("")
        self.btnAgregar_3.setCheckable(False)
        self.btnAgregar_3.setFlat(True)
        self.btnAgregar_3.setObjectName("btnAgregar_3")
        self.lblVariableScroll = QtWidgets.QScrollArea(self.MainFrame)
        self.lblVariableScroll.setGeometry(QtCore.QRect(90, 5, 90, 25))
        self.lblVariableScroll.setMinimumSize(QtCore.QSize(65, 20))
        self.lblVariableScroll.setMaximumSize(QtCore.QSize(100, 25))
        self.lblVariableScroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblVariableScroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblVariableScroll.setLineWidth(0)
        self.lblVariableScroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lblVariableScroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lblVariableScroll.setWidgetResizable(True)
        self.lblVariableScroll.setObjectName("lblVariableScroll")
        self.ScrollVariableLayout = QtWidgets.QWidget()
        self.ScrollVariableLayout.setGeometry(QtCore.QRect(0, 0, 90, 25))
        self.ScrollVariableLayout.setObjectName("ScrollVariableLayout")
        self._2 = QtWidgets.QVBoxLayout(self.ScrollVariableLayout)
        self._2.setContentsMargins(0, 0, 0, 0)
        self._2.setSpacing(0)
        self._2.setObjectName("_2")
        self.lblVariable = QtWidgets.QLabel(self.ScrollVariableLayout)
        self.lblVariable.setMaximumSize(QtCore.QSize(16666672, 16666672))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblVariable.setFont(font)
        self.lblVariable.setLineWidth(0)
        self.lblVariable.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lblVariable.setWordWrap(True)
        self.lblVariable.setIndent(5)
        self.lblVariable.setObjectName("lblVariable")
        self._2.addWidget(self.lblVariable)
        self.lblVariableScroll.setWidget(self.ScrollVariableLayout)

        self.retranslateUi(VariableWidget)
        QtCore.QMetaObject.connectSlotsByName(VariableWidget)

    def retranslateUi(self, VariableWidget):
        _translate = QtCore.QCoreApplication.translate
        VariableWidget.setWindowTitle(_translate("VariableWidget", "Form"))
        self.lblNombre.setText(_translate("VariableWidget", "AI0"))
        self.lblTipo.setText(_translate("VariableWidget", "Escritura"))
        self.lblColor.setText(_translate("VariableWidget", "-"))
        self.lblSel.setText(_translate("VariableWidget", "Analogica"))
        self.lblVariable.setText(_translate("VariableWidget", "AI0"))
