from classes.objects.workSpace import workSpace
from classes.logica import Logica
import json
from collections import namedtuple

access_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTAxODI1MTgsIm5iZiI6MTU5MDE4MjUxOCwianRpIjoiOGQxZjQyNDMtMDg3Yy00MjJlLTllNDAtY2Q5YzZmMjE2YmQ5IiwiZXhwIjoxNTkwMjY4OTE4LCJpZGVudGl0eSI6eyJJZCI6IjVkYTlmOWIxZWYyOGJkMjEyMDkxMGI0ZSIsIlVzdWFyaW8iOiJhZG1pbmlzdHJhZG9yLnNjYWRhIiwiVGlwbyI6IkFkbWluaXN0cmFkb3IifSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsiVGlwbyI6IkFkbWluaXN0cmFkb3IiLCJJZCI6IjVkYTlmOWIxZWYyOGJkMjEyMDkxMGI0ZSJ9fQ.YbPGqekW7Z_uR-xC6oj9l1VJRTsL7tL4CCfwepmU5pI"

result = Logica.ObtenerProyectos(**{"access_token":access_token})

json:workSpace = json.loads(json.dumps(result[0]),object_hook=workSpace)

print(json.toJSON())
