from classes import Logica,device

access_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTI3Nzk5NzIsIm5iZiI6MTU5Mjc3OTk3MiwianRpIjoiMDEwYzg0NjYtYWI5OS00NWU1LWJiNDQtODdlNTk2NjNmYTcyIiwiZXhwIjoxNTkyODY2MzcyLCJpZGVudGl0eSI6eyJJZCI6IjVkYTlmOWIxZWYyOGJkMjEyMDkxMGI0ZSIsIlVzdWFyaW8iOiJhZG1pbmlzdHJhZG9yLnNjYWRhIiwiVGlwbyI6IkFkbWluaXN0cmFkb3IifSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsiVGlwbyI6IkFkbWluaXN0cmFkb3IiLCJJZCI6IjVkYTlmOWIxZWYyOGJkMjEyMDkxMGI0ZSJ9fQ.s-623eA5oyjWUtBWTwwfxYvUU0WRpVXq0ycnq8Ej0Yk"


work = Logica.ObtenerWorkspaces(**{"access_token":access_token})
#work = Logica.AbrirProyectoDebug(**{"access_token":access_token,"id":"5ee7e324604b0e6ce89d3f49"})
print(work)
#for x in work:
#    print(x.__dict__)